export const cars = [
  {
    id: '1',
    userId: '001',
    author: 'John Doe',
    tel: '+996557184916',
    info: 'Ford F-150: 2023г. 2,7л. Автомат, Бензин',
    category: 'Продаю автомобиль',
    price: 5421900,
    moneySymbol: 'KGS',
    brand: 'Ford',
    model: 'F-150',
    year: 2023,
    gear: 'automatic',
    engineVolume: 2.7,
    stearingWheel: 'left',
    condition: 'Б/У',
    techCondition: 'Хорошее',
    docs: 'растаможен',
    ride: 9760,
    body: 'пикап',
    fuels: 'бензин',
    color: 'черный',
    drive: 'полный',
    isAvailability: true,
    payMethods: ['Оплата наличными', 'Расрочка'],
    vinCode: true,
    images: [
      {
        id: '6254654',
        name: 'Ford image',
        size: '755',
        url: 'https://media.ed.edmunds-media.com/ford/f-150/2023/oem/2023_ford_f-150_crew-cab-pickup_lariat_fq_oem_1_1280.jpg',
      },
    ],
    mainImage: {
      id: '6254654',
      name: 'Ford image',
      size: '755',
      url: 'https://media.ed.edmunds-media.com/ford/f-150/2023/oem/2023_ford_f-150_crew-cab-pickup_lariat_fq_oem_1_1280.jpg',
    },
  },
  {
    id: 2,
    userId: '056',
    author: 'John Doe',
    tel: '+996557184916',
    info: 'BMW M3 G80 Sedan Competition - 19 January 2022 - Autogespot',
    category: 'Продаю автомобиль',
    price: 5421900,
    moneySymbol: 'KGS',
    brand: 'BMW',
    model: 'M3',
    year: 2022,
    gear: 'automatic',
    engineVolume: 3.5,
    stearingWheel: 'left',
    condition: 'Б/У',
    techCondition: 'Хорошее',
    docs: 'растаможен',
    ride: 9760,
    body: 'пикап',
    fuels: 'бензин',
    color: 'черный',
    drive: 'полный',
    isAvailability: true,
    payMethods: ['Оплата наличными', 'Расрочка'],
    vinCode: true,
    images: [
      {
        id: '6254654',
        name: 'bmw',
        size: '755',
        url: 'https://static0.carbuzzimages.com/wordpress/wp-content/uploads/gallery-images/original/835000/0/835076.jpg',
      },
    ],
    mainImage: {
      id: '6254654',
      name: 'bmw',
      size: '755',
      url: 'https://spots.ag/2022/01/19/bmw-m3-g80-sedan-competition-c786219012022002723_1.jpg?1642548687',
    },
  },
  {
    id: 3,
    userId: '777',
    author: 'John Doe',
    tel: '+996557184916',
    info: "Here's An Illustrated Look At The 2022 BMW M3 Touring | Carscoops",
    category: 'Продаю автомобиль',
    price: 25000,
    moneySymbol: 'KGS',
    brand: 'BMW',
    model: 'M3',
    year: 2022,
    gear: 'automatic',
    engineVolume: 3.5,
    stearingWheel: 'left',
    condition: 'Б/У',
    techCondition: 'Хорошее',
    docs: 'растаможен',
    ride: 9760,
    body: 'пикап',
    fuels: 'бензин',
    color: 'черный',
    drive: 'полный',
    isAvailability: true,
    payMethods: ['Оплата наличными', 'Расрочка'],
    vinCode: true,
    images: [
      {
        id: '6254654',
        name: 'bmw',
        size: '755',
        url: 'https://images.kb-qatar.com/10329/6914/knightsbridge-automotive-lg.jpg',
      },
    ],
    mainImage: {
      id: '6254654',
      name: 'bmw',
      size: '755',
      url: 'https://www.carscoops.com/wp-content/uploads/2020/08/2022-bmw-m3-touring-render-0.jpg',
    },
  },
  {
    id: 4,
    userId: '111',
    author: 'John Doe',
    tel: '+996557184916',
    info: '2022 BMW M3 / M4 Competition: First Look - autoNXT.net',
    category: 'Продаю автомобиль',
    price: 30000,
    moneySymbol: 'KGS',
    brand: 'BMW',
    model: 'M3',
    year: 2022,
    gear: 'automatic',
    engineVolume: 3.5,
    stearingWheel: 'left',
    condition: 'Б/У',
    techCondition: 'Хорошее',
    docs: 'растаможен',
    ride: 9760,
    body: 'пикап',
    fuels: 'бензин',
    color: 'черный',
    drive: 'полный',
    isAvailability: true,
    payMethods: ['Оплата наличными', 'Расрочка'],
    vinCode: true,
    images: [
      {
        id: '6254654',
        name: 'bmw',
        size: '755',
        url: 'https://autonxt.net/wp-content/uploads/2021/04/2022_BMW_M4_Comp_xDrive_39.jpg',
      },
    ],
    mainImage: {
      id: '6254654',
      name: 'bmw',
      size: '755',
      url: 'https://autonxt.net/wp-content/uploads/2021/04/2022_BMW_M4_Comp_xDrive_39.jpg',
    },
  },
  {
    id: 5,
    userId: '001',
    author: 'Bryan Soles',
    tel: '+996557184916',
    info: '2022 BMW M3 / M4 Competition: First Look - autoNXT.net',
    category: 'Продаю автомобиль',
    price: 60000,
    moneySymbol: 'KGS',
    brand: 'BMW',
    model: 'M3',
    year: 2022,
    gear: 'automatic',
    engineVolume: 3.5,
    stearingWheel: 'left',
    condition: 'Б/У',
    techCondition: 'Хорошее',
    docs: 'растаможен',
    ride: 9760,
    body: 'пикап',
    fuels: 'бензин',
    color: 'черный',
    drive: 'полный',
    isAvailability: true,
    payMethods: ['Оплата наличными', 'Расрочка'],
    vinCode: true,
    images: [
      {
        id: '6254654',
        name: 'bmw',
        size: '755',
        url: 'https://spots.ag/2022/02/25/bmw-m3-g80-sedan-competition-c278525022022201758_1.jpg?1645816704',
      },
    ],
    mainImage: {
      id: '6254654',
      name: 'bmw',
      size: '755',
      url: 'https://spots.ag/2022/02/25/bmw-m3-g80-sedan-competition-c278525022022201758_1.jpg?1645816704',
    },
  },
  {
    id: 6,
    userId: '001',
    author: 'Dick Nilson',
    tel: '+996557184916',
    info: '2022 BMW M3 Competition xDrive First Drive & POV! Is it WORTH the Price?',
    category: 'Продаю автомобиль',
    price: 34500,
    moneySymbol: 'KGS',
    brand: 'BMW',
    model: 'M3',
    year: 2022,
    gear: 'automatic',
    engineVolume: 3.5,
    stearingWheel: 'left',
    condition: 'Б/У',
    techCondition: 'Хорошее',
    docs: 'растаможен',
    ride: 9760,
    body: 'пикап',
    fuels: 'бензин',
    color: 'черный',
    drive: 'полный',
    isAvailability: true,
    payMethods: ['Оплата наличными', 'Расрочка'],
    vinCode: true,
    images: [
      {
        id: '6254654',
        name: 'bmw',
        size: '755',
        url: 'https://i.ytimg.com/vi/C7rV5Kb7qaQ/maxresdefault.jpg',
      },
    ],
    mainImage: {
      id: '6254654',
      name: 'bmw',
      size: '755',
      url: 'https://i.ytimg.com/vi/C7rV5Kb7qaQ/maxresdefault.jpg',
    },
  },
  {
    id: 7,
    userId: '001',
    author: 'Bred Pit',
    tel: '+996557184916',
    info: '2022 BMW M3 Competition xDrive First Drive & POV! Is it WORTH the Price?',
    category: 'Продаю автомобиль',
    price: 36300,
    moneySymbol: 'KGS',
    brand: 'BMW',
    model: 'M3',
    year: 2022,
    gear: 'automatic',
    engineVolume: 3.5,
    stearingWheel: 'left',
    condition: 'Б/У',
    techCondition: 'Хорошее',
    docs: 'растаможен',
    ride: 9760,
    body: 'пикап',
    fuels: 'бензин',
    color: 'черный',
    drive: 'полный',
    isAvailability: true,
    payMethods: ['Оплата наличными', 'Расрочка'],
    vinCode: true,
    images: [
      {
        id: '6254654',
        name: 'bmw',
        size: '755',
        url: 'https://npr.brightspotcdn.com/0b/b2/c36c72ae4cab8c6461a81db07a42/bmw2.jpg',
      },
    ],
    mainImage: {
      id: '6254654',
      name: 'bmw',
      size: '755',
      url: 'https://npr.brightspotcdn.com/0b/b2/c36c72ae4cab8c6461a81db07a42/bmw2.jpg',
    },
  },
  {
    id: 8,
    userId: '001',
    author: 'Bill Winston',
    tel: '+996557184916',
    info: 'Used 2022 BMW M3 Competition xDrive For Sale (Sold) | Acton Auto Boutique Stock #M21732',
    category: 'Продаю автомобиль',
    price: 44800,
    moneySymbol: 'KGS',
    brand: 'BMW',
    model: 'M3',
    year: 2022,
    gear: 'automatic',
    engineVolume: 3.5,
    stearingWheel: 'left',
    condition: 'Б/У',
    techCondition: 'Хорошее',
    docs: 'растаможен',
    ride: 9760,
    body: 'пикап',
    fuels: 'бензин',
    color: 'черный',
    drive: 'полный',
    isAvailability: true,
    payMethods: ['Оплата наличными', 'Расрочка'],
    vinCode: true,
    images: [
      {
        id: '6254654',
        name: 'bmw',
        size: '755',
        url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQEAcCjiCd5wODpwQ1IkfzHp7nVvDP6GpG5g&s',
      },
    ],
    mainImage: {
      id: '6254654',
      name: 'bmw',
      size: '755',
      url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQEAcCjiCd5wODpwQ1IkfzHp7nVvDP6GpG5g&s',
    },
  },
  {
    id: 9,
    userId: '001',
    author: 'Bill Winston',
    tel: '+996557184916',
    info: 'Porsche reveals a new hybrid 911 as more consumers embrace hybrids over electric vehicles | CNN Business',
    category: 'Продаю автомобиль',
    price: 165000,
    moneySymbol: 'KGS',
    brand: 'Porsche',
    model: 'M3',
    year: 2022,
    gear: 'automatic',
    engineVolume: 3.5,
    stearingWheel: 'left',
    condition: 'Б/У',
    techCondition: 'Хорошее',
    docs: 'растаможен',
    ride: 9760,
    body: 'пикап',
    fuels: 'бензин',
    color: 'черный',
    drive: 'полный',
    isAvailability: true,
    payMethods: ['Оплата наличными', 'Расрочка'],
    vinCode: true,
    images: [
      {
        id: '6254654',
        name: 'bmw',
        size: '755',
        url: 'https://media.cnn.com/api/v1/images/stellar/prod/hi-res-porsche-911-hybrid.jpeg?c=original',
      },
    ],
    mainImage: {
      id: '6254654',
      name: 'bmw',
      size: '755',
      url: 'https://media.cnn.com/api/v1/images/stellar/prod/hi-res-porsche-911-hybrid.jpeg?c=original',
    },
  },
  {
    id: 10,
    userId: '001',
    author: 'Bill Winston',
    tel: '+996557184916',
    info: 'Прокат Порше | 911, Кайенна, Макан, Панамера, Тайкан',
    category: 'Продаю автомобиль',
    price: 1500,
    moneySymbol: 'KGS',
    brand: 'Porsche',
    model: 'M3',
    year: 2022,
    gear: 'automatic',
    engineVolume: 3.5,
    stearingWheel: 'left',
    condition: 'Б/У',
    techCondition: 'Хорошее',
    docs: 'растаможен',
    ride: 9760,
    body: 'пикап',
    fuels: 'бензин',
    color: 'черный',
    drive: 'полный',
    isAvailability: true,
    payMethods: ['Оплата наличными', 'Расрочка'],
    vinCode: true,
    images: [
      {
        id: '6254654',
        name: 'bmw',
        size: '755',
        url: 'https://deluxerentalcars.ch/wp-content/uploads/2024/05/Porsche-Carrera-4S-Cabrio_SEO-scaled.jpg',
      },
    ],
    mainImage: {
      id: '6254654',
      name: 'bmw',
      size: '755',
      url: 'https://deluxerentalcars.ch/wp-content/uploads/2024/05/Porsche-Carrera-4S-Cabrio_SEO-scaled.jpg',
    },
  },
  {
    id: 11,
    userId: '001',
    author: 'Nelly',
    tel: '+996557184916',
    info: 'Porsche Reports US Retail Sales for 2023 - Porsche Newsroom USA',
    category: 'Продаю автомобиль',
    price: 15600,
    moneySymbol: 'KGS',
    brand: 'Porsche',
    model: 'M3',
    year: 2022,
    gear: 'automatic',
    engineVolume: 3.5,
    stearingWheel: 'left',
    condition: 'Б/У',
    techCondition: 'Хорошее',
    docs: 'растаможен',
    ride: 9760,
    body: 'пикап',
    fuels: 'бензин',
    color: 'черный',
    drive: 'полный',
    isAvailability: true,
    payMethods: ['Оплата наличными', 'Расрочка'],
    vinCode: true,
    images: [
      {
        id: '6254654',
        name: 'bmw',
        size: '755',
        url: 'https://newsroom.porsche.com/.imaging/mte/porsche-templating-theme/image_1290x726/dam/US-local/2024/1.-JAN/2024112_Porsche_reports_US_retail_sales_for_2023/RubyStarNeo911.jpeg/jcr:content/RubyStarNeo911.jpeg',
      },
    ],
    mainImage: {
      id: '6254654',
      name: 'bmw',
      size: '755',
      url: 'https://newsroom.porsche.com/.imaging/mte/porsche-templating-theme/image_1290x726/dam/US-local/2024/1.-JAN/2024112_Porsche_reports_US_retail_sales_for_2023/RubyStarNeo911.jpeg/jcr:content/RubyStarNeo911.jpeg',
    },
  },
  {
    id: 12,
    userId: '001',
    author: 'James Wang',
    tel: '+996557184916',
    info: 'Ile pieniędzy potrzebujesz, aby jeździć Porsche? Mniej niż myślisz! - WyjątkowyPrezent.pl',
    category: 'Продаю автомобиль',
    price: 156000,
    moneySymbol: 'KGS',
    brand: 'Porsche',
    model: 'M3',
    year: 2022,
    gear: 'automatic',
    engineVolume: 3.5,
    stearingWheel: 'left',
    condition: 'Б/У',
    techCondition: 'Хорошее',
    docs: 'растаможен',
    ride: 9760,
    body: 'пикап',
    fuels: 'бензин',
    color: 'черный',
    drive: 'полный',
    isAvailability: true,
    payMethods: ['Оплата наличными', 'Расрочка'],
    vinCode: true,
    images: [
      {
        id: '6254654',
        name: 'bmw',
        size: '755',
        url: 'https://www.wyjatkowyprezent.pl/blog/wp-content/uploads/2024/03/emoti__realistic_photo_of_a_pors.jpg',
      },
    ],
    mainImage: {
      id: '6254654',
      name: 'bmw',
      size: '755',
      url: 'https://www.wyjatkowyprezent.pl/blog/wp-content/uploads/2024/03/emoti__realistic_photo_of_a_pors.jpg',
    },
  },
  {
    id: 13,
    userId: '001',
    author: 'James Wang',
    tel: '+996557184916',
    info: '2025 Ford Expedition Review, Pricing, and Specs',
    category: 'Продаю автомобиль',
    price: 156000,
    moneySymbol: 'KGS',
    brand: 'Ford',
    model: 'Raptor',
    year: 2022,
    gear: 'automatic',
    engineVolume: 3.5,
    stearingWheel: 'left',
    condition: 'Б/У',
    techCondition: 'Хорошее',
    docs: 'растаможен',
    ride: 9760,
    body: 'пикап',
    fuels: 'бензин',
    color: 'черный',
    drive: 'полный',
    isAvailability: true,
    payMethods: ['Оплата наличными', 'Расрочка'],
    vinCode: true,
    images: [
      {
        id: '6254654',
        name: 'bmw',
        size: '755',
        url: 'https://hips.hearstapps.com/hmg-prod/images/2025-ford-expedition-stealth-performance-exterior-108-66fadf15d18f2.jpg',
      },
    ],
    mainImage: {
      id: '6254654',
      name: 'bmw',
      size: '755',
      url: 'https://hips.hearstapps.com/hmg-prod/images/2025-ford-expedition-stealth-performance-exterior-108-66fadf15d18f2.jpg',
    },
  },
  {
    id: 14,
    userId: '001',
    author: 'Daston',
    tel: '+996557184916',
    info: 'Ford Mustang GT 5.0 - SWS Cars',
    category: 'Продаю автомобиль',
    price: 37800,
    moneySymbol: 'KGS',
    brand: 'Ford',
    model: 'Mustang',
    year: 2022,
    gear: 'automatic',
    engineVolume: 3.5,
    stearingWheel: 'left',
    condition: 'Б/У',
    techCondition: 'Хорошее',
    docs: 'растаможен',
    ride: 9760,
    body: 'пикап',
    fuels: 'бензин',
    color: 'черный',
    drive: 'полный',
    isAvailability: true,
    payMethods: ['Оплата наличными', 'Расрочка'],
    vinCode: true,
    images: [
      {
        id: '6254654',
        name: 'bmw',
        size: '755',
        url: 'https://sws-cars.pl/wp-content/uploads/2021/11/ford-mustang-image.jpg',
      },
    ],
    mainImage: {
      id: '6254654',
      name: 'bmw',
      size: '755',
      url: 'https://sws-cars.pl/wp-content/uploads/2021/11/ford-mustang-image.jpg',
    },
  },
]
